name: PowerShell script
author: Freddy Kristiansen
inputs:
  project:
    description: Project folder
    required: false
    default: '.'
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
runs:
  using: composite
  steps:
    - name: run
      shell: PowerShell
      env:
        _project: ${{ inputs.project }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
      run: try { ${{ github.action_path }}/PipelineCleanup.ps1 -project $ENV:_project -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
