name: PowerShell script
author: Freddy Kristiansen
inputs:
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  project:
    description: Project folder
    required: false
    default: '.'
  getprojects:
    description: Indicates whether you want to retrieve the list of project list as well
    required: false
    default: 'N'
  getenvironments:
    description: Specifies the pattern of the environments you want to retreive (or empty for no environments)
    required: false
    default: ''
  includeProduction:
    description: Specifies whether you want to include production environments
    required: false
    default: 'N'
  release:
    description: Indicates whether this is called from a release pipeline
    required: false
    default: 'N'
  get:
    description: Specifies which properties to get from the settings file, default is all
    required: false
    default: ''
outputs:
  SettingsJson:
    description: Settings in compressed Json format
    value: ${{ steps.readsettings.outputs.SettingsJson }}
  GitHubRunnerJson:
    description: GitHubRunner in compressed Json format
    value: ${{ steps.readsettings.outputs.GitHubRunnerJson }}
  ProjectsJson:
    description: Projects in compressed Json format
    value: ${{ steps.readsettings.outputs.ProjectsJson }}
  ProjectCount:
    description: Number of projects in array
    value: ${{ steps.readsettings.outputs.ProjectCount }}
  EnvironmentsJson:
    description: Environments in compressed Json format
    value: ${{ steps.readsettings.outputs.EnvironmentsJson }}
  EnvironmentCount:
    description: Number of environments in array
    value: ${{ steps.readsettings.outputs.EnvironmentCount }}
  ProjectDependenciesJson:
    description: Project Dependencies Json
    value: ${{ steps.readsettings.outputs.ProjectDependenciesJson }}
  BuildOrderJson:
    description: Build order Json
    value: ${{ steps.readsettings.outputs.BuildOrderJson }}
  BuildOrderDepth:
    description: Depth in build order
    value: ${{ steps.readsettings.outputs.BuildOrderDepth }}
runs:
  using: composite
  steps:
    - name: run
      shell: PowerShell
      id: readsettings
      env:
        _actor: ${{ inputs.actor }}
        _token: ${{ inputs.token }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        _project: ${{ inputs.project }}
        _getprojects: ${{ inputs.getprojects }}
        _getenvironments: ${{ inputs.getenvironments }}
        _includeProduction: ${{ inputs.includeProduction }}
        _release: ${{ inputs.release }}
        _get: ${{ inputs.get }}
      run: try { ${{ github.action_path }}/ReadSettings.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -project $ENV:_project -getprojects ($ENV:_getprojects -eq 'Y') -getenvironments $ENV:_getenvironments -includeProduction ($ENV:_includeProduction -eq 'Y') -release ($ENV:_release -eq 'Y') -get $ENV:_get } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
