name: PowerShell script
author: Freddy Kristiansen
inputs:
  settingsJson:
    description: Settings from template repository in compressed Json format
    required: false
    default: '{"keyVaultName": ""}'
  secrets:
    description: Comma separated list of Secrets to get
    required: true
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
runs:
  using: composite
  steps:
    - name: run
      shell: PowerShell
      env:
        _settingsJson: ${{ inputs.settingsJson }}
        _secrets: ${{ inputs.secrets }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
      run: try { ${{ github.action_path }}/ReadSecrets.ps1 -settingsJson $ENV:_settingsJson -secrets $ENV:_secrets -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
